ManagingMultijQueryForm/ManagingMultijQueryForm/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManagingMultijQueryForm.Models;

namespace ManagingMultijQueryForm.Controllers
{
    public class CategoryController : Controller
    {
        ProductDbContext db = new ProductDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Get(int id)
        {
            var category = db.Category.Find(id);

            return Json(new { Id = category.CategoryID, Name = category.Name }, "application/json", JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult List()
        {
            return PartialView("_CategoryList", db.Category.ToList());
        }

        [HttpPost]
        public PartialViewResult List(string s)
        {
            return PartialView("_CategoryList", db.Category.Where(m => m.Name.Contains(s)).ToList());
        }

        public PartialViewResult Add()
        {
            return PartialView("_Category");
        }

        [HttpPost, ValidationActionFilter]
        public PartialViewResult Add(Category model)
        {
            db.Category.Add(model);
            db.SaveChanges();

            return Add();
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            var category = db.Category.Find(id);

            db.Category.Remove(category);
            db.SaveChanges();

            return Json(new { success = true, message = "Record deleted successfully!" }, "application/json", JsonRequestBehavior.AllowGet);
        }
    }
}

ManagingMultijQueryForm/ManagingMultijQueryForm/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManagingMultijQueryForm.Models;

namespace ManagingMultijQueryForm.Controllers
{
    public class SubCategoryController : Controller
    {
        ProductDbContext db = new ProductDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Get(int id)
        {
            var subcategory  = db.SubCategory.Find(id);

            return Json(new { Id = subcategory.SubCategoryID, Name = subcategory.Name }, "application/json", JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult List()
        {
            return PartialView("_SubCategoryList", db.SubCategory.ToList());
        }

        [HttpPost]
        public PartialViewResult List(string s)
        {
            return PartialView("_SubCategoryList", db.SubCategory.Where(m => m.Name.Contains(s) || m.Category.Name.Contains(s)).ToList());
        }

        public PartialViewResult Add()
        {
            return PartialView("_SubCategory");
        }

        [HttpPost, ValidationActionFilter]
        public PartialViewResult Add(SubCategory model)
        {
            db.SubCategory.Add(model);
            db.SaveChanges();

            return Add();
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            var subcategory = db.SubCategory.Find(id);

            db.SubCategory.Remove(subcategory);
            db.SaveChanges();

            return Json(new { success = true, message = "Record deleted successfully!" }, "application/json", JsonRequestBehavior.AllowGet);
        }
    }
}

ManagingMultijQueryForm/ManagingMultijQueryForm/Views/SubCategory/_SubCategory.cshtml
@model ManagingMultijQueryForm.Models.SubCategory

@using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "closeDialog();updateSection();", OnFailure = "onAjaxFailure" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SubCategory</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryID)
        </div>
        <div class="editor-field">
            <input type="text" value="@(Model != null ? Model.Category.Name : "")" disabled="disabled" />
            @Html.HiddenFor(model => model.CategoryID)
            @Html.ValidationMessageFor(model => model.CategoryID)
            @Html.ImageActionLink(Url.Content("~/Content/Images/Icons/search.png"), "Browse Category", "List", "Category", null, new { @class = "dialog", @title = "Category", }, new { border = 0 })
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
    <script>
        $(function () {
            $("img").button();
        });
    </script>
}

ManagingMultijQueryForm/ManagingMultijQueryForm/Views/SubCategory/_SubCategoryList.cshtml
@model IEnumerable<ManagingMultijQueryForm.Models.SubCategory>

@using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "updateSearchContainer" }))
{
    <p>
        @Html.TextBox("s")
        <input type="submit" value="Search" />
        @Html.ActionLink("Create New", "Add", "SubCategory", null, new { @class = "dialog ahref", @title = "Add Sub Category" })
    </p>
}
@{
    var grid = new WebGrid(
        Model, rowsPerPage: 10,
        defaultSort: "Name",
        ajaxUpdateContainerId: "subcategoryList");
}

<div id="subcategoryList">

    @grid.GetHtml(
            fillEmptyRows: false,
            mode: WebGridPagerModes.All,

            tableStyle: "webgrid-table",
            headerStyle: "webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "webgrid-alternating-row",
            rowStyle: "webgrid-row-style",

            columns: grid.Columns
            (
                grid.Column("", format: (a) => @Ajax.ActionLink("Select", "Get", "SubCategory", new { @id = a.SubCategoryID }, new AjaxOptions { OnSuccess = "updateContainer" }), header: ""),
                grid.Column("Name", header: "Name " + WebGridSortHelper.SortDirection(null, ref grid, "Name")),
                grid.Column("Category.Name", header: "Category " + WebGridSortHelper.SortDirection(null, ref grid, "Category.Name")),
                grid.Column("", format: (a) => @Html.ActionLink("Delete", "Delete", "SubCategory", new { @id = a.SubCategoryID }, new { @class = "delete", @title = "Delete" }), header: "")
            )
        )
</div>

<script>
    $("a.ahref, input[type='submit']").button();
</script>