ManagingMultijQueryForm/ManagingMultijQueryForm/Models/Product.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace ManagingMultijQueryForm.Models
{
    public class Product
    {
        public int ProductID { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [Required]
        [StringLength(250)]
        public string Description { get; set; }

        public virtual SubCategory SubCategory { get; set; }

        [Display(Name = "Sub Category")]
        public int SubCategoryID { get; set; }
    }

    public class Category
    {
        public int CategoryID { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }
    }

    public class SubCategory
    {
        public int SubCategoryID { get; set; }

        public virtual Category Category { get; set; }

        [Display(Name = "Category")]
        public int CategoryID { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }
    }

    public class ProductDbContext : DbContext
    {
        public ProductDbContext()
            : base(nameOrConnectionString: "Data Source=PCI7-JFUENTES\\SQL_JF;Initial Catalog=Taller;Integrated Security=true;")
        {
            Database.SetInitializer(new ProductDbContextInitializer());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Use singular table names
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            base.OnModelCreating(modelBuilder);
        }

        public DbSet<Product> Product { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<SubCategory> SubCategory { get; set; }
    }

    public class ProductDbContextInitializer : DropCreateDatabaseIfModelChanges<ProductDbContext>
    {
        protected override void Seed(ProductDbContext context)
        {
            List<Category> categories = new List<Category>
            {
                new Category { Name = "Food" },
                new Category { Name = "Electronics" },
                new Category { Name = "Beverages" }
            };

            List<SubCategory> subcategories = new List<SubCategory>
            {
                new SubCategory { Name = "Vegetables", Category = categories.Find(m => m.Name.Equals("Food")) },
                new SubCategory { Name = "Fruits", Category = categories.Find(m => m.Name.Equals("Food")) },
                new SubCategory { Name = "Computer", Category = categories.Find(m => m.Name.Equals("Electronics")) },
                new SubCategory { Name = "Television", Category = categories.Find(m => m.Name.Equals("Electronics")) },
                new SubCategory { Name = "Cold Drinks", Category = categories.Find(m => m.Name.Equals("Beverages")) },
                new SubCategory { Name = "Beer", Category = categories.Find(m => m.Name.Equals("Beverages")) },
            };

            List<Product> products = new List<Product>
            {
                new Product { Name = "Wheat", Description = "Wheat", SubCategory = subcategories.Find(m => m.Name.Equals("Vegetables")) },
                new Product { Name = "Apple", Description = "Apple", SubCategory = subcategories.Find(m => m.Name.Equals("Fruits")) },
                new Product { Name = "Desktop", Description = "Desktop", SubCategory = subcategories.Find(m => m.Name.Equals("Computer")) },
                new Product { Name = "LG", Description = "LG", SubCategory = subcategories.Find(m => m.Name.Equals("Television")) },
                new Product { Name = "Sprite", Description = "Sprite", SubCategory = subcategories.Find(m => m.Name.Equals("Cold Drinks")) },
                new Product { Name = "Kingfisher", Description = "Kingfisher", SubCategory = subcategories.Find(m => m.Name.Equals("Beer")) },
            };

            categories.ForEach(m => context.Category.Add(m));
            subcategories.ForEach(m => context.SubCategory.Add(m));
            products.ForEach(m => context.Product.Add(m));

            context.SaveChanges();

            base.Seed(context);
        }
    }
}

ManagingMultijQueryForm/ManagingMultijQueryForm/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManagingMultijQueryForm.Models;

namespace ManagingMultijQueryForm.Controllers
{
    public class ProductController : Controller
    {
        ProductDbContext db = new ProductDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return PartialView("_ProductList", db.Product.ToList());
        }

        public ActionResult Chao()
        {
            return View();
        }



        public PartialViewResult Add()
        {
            return PartialView("_Product");
        }

        [HttpPost, ValidationActionFilter]
        public PartialViewResult Add(Product model,FormCollection form=null)
        {
            db.Product.Add(model);
            db.SaveChanges();

            return Add();
        }

        public PartialViewResult Edit(int id)
        {
            return PartialView("_Product", db.Product.Find(id));
        }

        [HttpPost, ValidationActionFilter]
        public PartialViewResult Edit(Product model)
        {
            var product = db.Product.Find(model.ProductID);

            db.Entry(product).CurrentValues.SetValues(model);
            db.SaveChanges();

            return Add();
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            var product = db.Product.Find(id);

            db.Product.Remove(product);
            db.SaveChanges();

            return Json(new { success = true, message = "Record deleted successfully!" }, "application/json", JsonRequestBehavior.AllowGet);
        }
    }
}

ManagingMultijQueryForm/ManagingMultijQueryForm/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManagingMultijQueryForm.Models;

namespace ManagingMultijQueryForm.Controllers
{
    public class SubCategoryController : Controller
    {
        ProductDbContext db = new ProductDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Get(int id)
        {
            var subcategory  = db.SubCategory.Find(id);

            return Json(new { Id = subcategory.SubCategoryID, Name = subcategory.Name }, "application/json", JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult List()
        {
            return PartialView("_SubCategoryList", db.SubCategory.ToList());
        }

        [HttpPost]
        public PartialViewResult List(string s)
        {
            return PartialView("_SubCategoryList", db.SubCategory.Where(m => m.Name.Contains(s) || m.Category.Name.Contains(s)).ToList());
        }

        public PartialViewResult Add()
        {
            return PartialView("_SubCategory");
        }

        [HttpPost, ValidationActionFilter]
        public PartialViewResult Add(SubCategory model)
        {
            db.SubCategory.Add(model);
            db.SaveChanges();

            return Add();
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            var subcategory = db.SubCategory.Find(id);

            db.SubCategory.Remove(subcategory);
            db.SaveChanges();

            return Json(new { success = true, message = "Record deleted successfully!" }, "application/json", JsonRequestBehavior.AllowGet);
        }
    }
}

ManagingMultijQueryForm/ManagingMultijQueryForm/Views/Product/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/GridStyle.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.10.4.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/app.js"></script>
</head>
<body>
    <!-- this div is for custom message box-->
    <!-- start -->
    <div id="dialog" title="Alert message" style="display: none">
        <div class="ui-dialog-content ui-widget-content">
            <p>
                <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0"></span>
                <label id="lblMessage">
                </label>
            </p>
        </div>
    </div>
    <!--  end -->

    <div id="productList">
       @* @using (Ajax.BeginForm("List", new AjaxOptions { }))
        {
            *@
        <div>
                @Html.ActionLink("Add Product", "Add", null, new { @class = "dialog button", @title = "Add Product" })

                @Html.ActionLink("Chao", "Chao", null, new { @class = "dialog button", @title = "Add Product" })


            </div>
        @*
            <div id="product-grid">

            </div>
                  
        }*@
    </div>
    <script>
        $(function () {

            $("a.button").button();
        });
    </script>
</body>
</html>

ManagingMultijQueryForm/ManagingMultijQueryForm/Views/Product/_Product.cshtml
@model ManagingMultijQueryForm.Models.Product

@using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "closeDialog();updateSection();", OnFailure = "onAjaxFailure" }))
{
    @Html.ValidationSummary(true)
    if (Model != null)
    {
        @Html.HiddenFor(m => m.ProductID)
    }
    
    <fieldset>
        <legend>Product</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubCategoryID)
        </div>
        <div class="editor-field">
            <input type="text" disabled="disabled" value="@(Model != null ? Model.SubCategory.Name : "")" />
            @Html.HiddenFor(model => model.SubCategoryID)
            @Html.ValidationMessageFor(model => model.SubCategoryID)
            @Html.ImageActionLink(Url.Content("~/Content/Images/Icons/search.png"), "Browse Sub Category", "List", "SubCategory", null, new { @class = "dialog", @title = "Sub Category" }, new { border = 0 })
        </div>

        <p>
            <input type="submit" value="@(Model != null ? "Update" : "Create")" />
        </p>
    </fieldset>
    <script>
        $(function () {
            $("img").button();
        });
    </script>
}

ManagingMultijQueryForm/ManagingMultijQueryForm/Views/Product/_ProductList.cshtml
@model IEnumerable<ManagingMultijQueryForm.Models.Product>

@{
    var grid = new WebGrid(
        Model, rowsPerPage: 10,
        defaultSort: "Name", ajaxUpdateContainerId: "product-grid");
}

@grid.GetHtml(
            fillEmptyRows: false,
            mode: WebGridPagerModes.All,

            tableStyle: "webgrid-table",
            headerStyle: "webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "webgrid-alternating-row",
            rowStyle: "webgrid-row-style",

            columns: grid.Columns
            (
                grid.Column("Name", header: "Name " + WebGridSortHelper.SortDirection(null, ref grid, "Name")),
                grid.Column("Description", header: "Description " + WebGridSortHelper.SortDirection(null, ref grid, "Description")),
                grid.Column("SubCategory.Name", header: "SubCategory " + WebGridSortHelper.SortDirection(null, ref grid, "SubCategory.Name")),
                grid.Column("SubCategory.Category.Name", header: "Category " + WebGridSortHelper.SortDirection(null, ref grid, "SubCategory.Category.Name")),
                grid.Column("", format: (a) => @Html.ActionLink("Edit", "Edit", "Product", new { @id = a.ProductID }, new { @class = "dialog", @title = "Edit" }), header: ""),
                grid.Column("", format: (a) => @Html.ActionLink("Delete", "Delete", "Product", new { @id = a.ProductID }, new { @class = "delete", @title = "Delete" }), header: "")
            )
)